name: Android Kernel Build
on: [push, workflow_dispatch]

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run Build Commands
        run: |
          export PLATFORM_VERSION=11
          export ANDROID_MAJOR_VERSION=r 
          export ARCH=arm64
          export SEC_BUILD_CONF_VENDOR_BUILD_OS=13
          make exynos9830-x1slte_defconfig
          make
